/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jinputtest;

import java.awt.Color;
import javax.swing.JLabel;
import net.java.games.input.Controller;
import net.java.games.input.Event;

/**
 *
 * @author alexa
 */
public class mw extends javax.swing.JFrame {

    Joystick joystick = null;
    
    /**
     * Creates new form mw
     */
    public mw() {
        initComponents();
        
        joystick = new Joystick(this);
        joystick.start();
        
        jl_carre.setForeground(Color.red);
        jl_croix.setForeground(Color.red);
        jl_rond.setForeground(Color.red);
        jl_triangle.setForeground(Color.red);
        
        jl_r1.setForeground(Color.red);
        jl_r2.setForeground(Color.red);
        jl_l1.setForeground(Color.red);
        jl_l2.setForeground(Color.red);
        jl_r3.setForeground(Color.red);
        jl_l3.setForeground(Color.red);
        
        jl_select.setForeground(Color.red);
        jl_screen.setForeground(Color.red);
        jl_home.setForeground(Color.red);
        jl_start.setForeground(Color.red);
        
        jl_zb.setForeground(Color.red);
        jl_zd.setForeground(Color.red);
        jl_zg.setForeground(Color.red);
        jl_zh.setForeground(Color.red);
        
        jl_croix_b.setForeground(Color.red);
        jl_croix_d.setForeground(Color.red);
        jl_croix_g.setForeground(Color.red);
        jl_croix_h.setForeground(Color.red);
        
        jl_x_d.setForeground(Color.red);
        jl_x_g.setForeground(Color.red);
        jl_y_b.setForeground(Color.red);
        jl_y_h.setForeground(Color.red);
        
    }

    public void setColorBool(Event e, JLabel jl)
    {
        if(e.getValue() == 1.0f)
        {
            jl.setForeground(Color.green);
        }
        else
        {
            jl.setForeground(Color.red);
        }
    }
    
    public void setColorJoy(Event e, JLabel jl1, JLabel jl2)
    {
        if(e.getValue() > 0)
        {
            jl1.setForeground(Color.green);
            jl2.setForeground(Color.red);
        }
        else if(e.getValue() < -0.01)
        {
            jl2.setForeground(Color.green);
            jl1.setForeground(Color.red);
        }
        else
        {
            jl2.setForeground(Color.red);
            jl1.setForeground(Color.red);
        }
    }
    
    public void Upd(Controller c, Event e)
    {
        
        switch(String.valueOf(e.getComponent().getIdentifier()))
        {
            case "0" :     setColorBool(e, jl_carre);
                        break;
                        
            case "1" :     setColorBool(e, jl_croix);
                        break;
                        
            case "2" :     setColorBool(e, jl_rond);
                        break;
                        
            case "3" :     setColorBool(e, jl_triangle);
                        break;
                        
            case "4" :     setColorBool(e, jl_l1);
                        break;
                        
            case "5" :     setColorBool(e, jl_r1);
                        break;
                        
            case "6" :     setColorBool(e, jl_l2);
                        break;
                        
            case "7" :     setColorBool(e, jl_r2);
                        break;
                        
            case "8" :     setColorBool(e, jl_select);
                        break;
                        
            case "9" :     setColorBool(e, jl_start);
                        break;
                        
            case "10" :    setColorBool(e, jl_l3);
                        break;
                        
            case "11" :    setColorBool(e, jl_r3);
                        break;
                        
            case "12" :    setColorBool(e, jl_home);
                        break;
                        
            case "13" :    setColorBool(e, jl_screen);
                        break;
                        
            case "z" :      setColorJoy(e, jl_zd, jl_zg);
                        break;
                        
            case "rz" :     setColorJoy(e, jl_zb, jl_zh);
                        break;
                        
            case "x" :      setColorJoy(e, jl_x_d, jl_x_g);
                        break;
                        
            case "y" :      setColorJoy(e, jl_y_b, jl_y_h);
                        break;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_carre = new javax.swing.JLabel();
        jl_croix = new javax.swing.JLabel();
        jl_rond = new javax.swing.JLabel();
        jl_triangle = new javax.swing.JLabel();
        jl_r1 = new javax.swing.JLabel();
        jl_r2 = new javax.swing.JLabel();
        jl_l1 = new javax.swing.JLabel();
        jl_l2 = new javax.swing.JLabel();
        jl_select = new javax.swing.JLabel();
        jl_screen = new javax.swing.JLabel();
        jl_home = new javax.swing.JLabel();
        jl_start = new javax.swing.JLabel();
        jl_zh = new javax.swing.JLabel();
        jl_zd = new javax.swing.JLabel();
        jl_zb = new javax.swing.JLabel();
        jl_zg = new javax.swing.JLabel();
        jl_croix_h = new javax.swing.JLabel();
        jl_croix_d = new javax.swing.JLabel();
        jl_croix_b = new javax.swing.JLabel();
        jl_croix_g = new javax.swing.JLabel();
        jl_y_h = new javax.swing.JLabel();
        jl_x_d = new javax.swing.JLabel();
        jl_y_b = new javax.swing.JLabel();
        jl_x_g = new javax.swing.JLabel();
        jl_l3 = new javax.swing.JLabel();
        jl_r3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jl_carre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_carre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_carre.setText("☐");

        jl_croix.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_croix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_croix.setText("X");

        jl_rond.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_rond.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_rond.setText("O");

        jl_triangle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_triangle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_triangle.setText("∆");
        jl_triangle.setToolTipText("");

        jl_r1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_r1.setText("R1");

        jl_r2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_r2.setText("R2");

        jl_l1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_l1.setText("L1");

        jl_l2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_l2.setText("L2");

        jl_select.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_select.setText("select");

        jl_screen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_screen.setText("screen");

        jl_home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_home.setText("home");

        jl_start.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_start.setText("start");

        jl_zh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_zh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_zh.setText("↑");

        jl_zd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_zd.setText("→\t");

        jl_zb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_zb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_zb.setText("↓");

        jl_zg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_zg.setText("←\t");

        jl_croix_h.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_croix_h.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_croix_h.setText("↑");

        jl_croix_d.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_croix_d.setText("→\t");

        jl_croix_b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_croix_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_croix_b.setText("↓");

        jl_croix_g.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_croix_g.setText("←\t");

        jl_y_h.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_y_h.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_y_h.setText("↑");

        jl_x_d.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_x_d.setText("→\t");

        jl_y_b.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_y_b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_y_b.setText("↓");

        jl_x_g.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_x_g.setText("←\t");

        jl_l3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_l3.setText("O");

        jl_r3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_r3.setText("O");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jl_l1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jl_y_b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jl_y_h, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl_r1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jl_rond, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_l2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jl_r2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl_r3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_triangle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_croix, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_zd, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(110, 110, 110))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl_zh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jl_x_g, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jl_l3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jl_x_d, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jl_select)
                                .addGap(89, 89, 89)
                                .addComponent(jl_start, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jl_screen, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jl_croix_h, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jl_croix_b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_home)
                                .addGap(33, 33, 33)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_croix_g, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jl_croix_d, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_carre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jl_zb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jl_zg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))
                        .addGap(146, 146, 146))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_r2)
                    .addComponent(jl_l2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_r1)
                    .addComponent(jl_l1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_select)
                    .addComponent(jl_start))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_screen)
                                    .addComponent(jl_home))
                                .addGap(8, 8, 8)
                                .addComponent(jl_triangle)
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_carre)
                                    .addComponent(jl_rond))
                                .addGap(18, 18, 18)
                                .addComponent(jl_croix))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_y_h)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_x_d)
                                    .addComponent(jl_x_g)
                                    .addComponent(jl_l3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_y_b)))
                        .addGap(52, 52, 52)
                        .addComponent(jl_zh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_zd)
                            .addComponent(jl_zg)
                            .addComponent(jl_r3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_zb))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_croix_h)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_croix_d)
                            .addComponent(jl_croix_g))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_croix_b)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mw().setVisible(true);
            }
        });
        
        
        
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jl_carre;
    private javax.swing.JLabel jl_croix;
    private javax.swing.JLabel jl_croix_b;
    private javax.swing.JLabel jl_croix_d;
    private javax.swing.JLabel jl_croix_g;
    private javax.swing.JLabel jl_croix_h;
    private javax.swing.JLabel jl_home;
    private javax.swing.JLabel jl_l1;
    private javax.swing.JLabel jl_l2;
    private javax.swing.JLabel jl_l3;
    private javax.swing.JLabel jl_r1;
    private javax.swing.JLabel jl_r2;
    private javax.swing.JLabel jl_r3;
    private javax.swing.JLabel jl_rond;
    private javax.swing.JLabel jl_screen;
    private javax.swing.JLabel jl_select;
    private javax.swing.JLabel jl_start;
    private javax.swing.JLabel jl_triangle;
    private javax.swing.JLabel jl_x_d;
    private javax.swing.JLabel jl_x_g;
    private javax.swing.JLabel jl_y_b;
    private javax.swing.JLabel jl_y_h;
    private javax.swing.JLabel jl_zb;
    private javax.swing.JLabel jl_zd;
    private javax.swing.JLabel jl_zg;
    private javax.swing.JLabel jl_zh;
    // End of variables declaration//GEN-END:variables
}
